"""add  raw_order_documents table and raw_order_items table

Revision ID: f29d133cc07c
Revises: 71f58c76dee5
Create Date: 2025-11-10 14:28:16.146277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29d133cc07c'
down_revision: Union[str, Sequence[str], None] = '71f58c76dee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_order_documents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=False),
    sa.Column('cashier_id', sa.BigInteger(), nullable=False),
    sa.Column('order_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_index(op.f('ix_raw_order_documents_order_timestamp'), 'raw_order_documents', ['order_timestamp'], unique=False)
    op.create_table('raw_order_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=False),
    sa.Column('product_code', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_before_discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_order_items_document_number'), 'raw_order_items', ['document_number'], unique=False)
    op.alter_column('customer_analytics', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('employee_performance', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_sales_summary', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('raw_sales_events', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_sales_events', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_sales_summary', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('employee_performance', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customer_analytics', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_raw_order_items_document_number'), table_name='raw_order_items')
    op.drop_table('raw_order_items')
    op.drop_index(op.f('ix_raw_order_documents_order_timestamp'), table_name='raw_order_documents')
    op.drop_table('raw_order_documents')
    # ### end Alembic commands ###
