// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: analytics/analytics_service.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PaginationResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_analytics_analytics_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{2}
}

func (x *DateRange) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DateRange) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type SalesSummaryDaily struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date              string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	CashierId         int64                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalItemsSold    int32                  `protobuf:"varint,5,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	GrossSales        string                 `protobuf:"bytes,6,opt,name=gross_sales,json=grossSales,proto3" json:"gross_sales,omitempty"`
	TotalDiscounts    string                 `protobuf:"bytes,7,opt,name=total_discounts,json=totalDiscounts,proto3" json:"total_discounts,omitempty"`
	NetSales          string                 `protobuf:"bytes,8,opt,name=net_sales,json=netSales,proto3" json:"net_sales,omitempty"`
	TotalTax          string                 `protobuf:"bytes,9,opt,name=total_tax,json=totalTax,proto3" json:"total_tax,omitempty"`
	TotalCost         string                 `protobuf:"bytes,10,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	GrossProfit       string                 `protobuf:"bytes,11,opt,name=gross_profit,json=grossProfit,proto3" json:"gross_profit,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SalesSummaryDaily) Reset() {
	*x = SalesSummaryDaily{}
	mi := &file_analytics_analytics_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesSummaryDaily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesSummaryDaily) ProtoMessage() {}

func (x *SalesSummaryDaily) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesSummaryDaily.ProtoReflect.Descriptor instead.
func (*SalesSummaryDaily) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{3}
}

func (x *SalesSummaryDaily) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SalesSummaryDaily) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SalesSummaryDaily) GetCashierId() int64 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *SalesSummaryDaily) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *SalesSummaryDaily) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

func (x *SalesSummaryDaily) GetGrossSales() string {
	if x != nil {
		return x.GrossSales
	}
	return ""
}

func (x *SalesSummaryDaily) GetTotalDiscounts() string {
	if x != nil {
		return x.TotalDiscounts
	}
	return ""
}

func (x *SalesSummaryDaily) GetNetSales() string {
	if x != nil {
		return x.NetSales
	}
	return ""
}

func (x *SalesSummaryDaily) GetTotalTax() string {
	if x != nil {
		return x.TotalTax
	}
	return ""
}

func (x *SalesSummaryDaily) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

func (x *SalesSummaryDaily) GetGrossProfit() string {
	if x != nil {
		return x.GrossProfit
	}
	return ""
}

func (x *SalesSummaryDaily) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SalesSummaryDaily) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductSalesSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date           string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	ProductId      int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductGroupId *int32                 `protobuf:"varint,4,opt,name=product_group_id,json=productGroupId,proto3,oneof" json:"product_group_id,omitempty"`
	QuantitySold   int32                  `protobuf:"varint,5,opt,name=quantity_sold,json=quantitySold,proto3" json:"quantity_sold,omitempty"`
	GrossSales     string                 `protobuf:"bytes,6,opt,name=gross_sales,json=grossSales,proto3" json:"gross_sales,omitempty"`
	TotalDiscounts string                 `protobuf:"bytes,7,opt,name=total_discounts,json=totalDiscounts,proto3" json:"total_discounts,omitempty"`
	NetSales       string                 `protobuf:"bytes,8,opt,name=net_sales,json=netSales,proto3" json:"net_sales,omitempty"`
	TotalCost      string                 `protobuf:"bytes,9,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	GrossProfit    string                 `protobuf:"bytes,10,opt,name=gross_profit,json=grossProfit,proto3" json:"gross_profit,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductSalesSummary) Reset() {
	*x = ProductSalesSummary{}
	mi := &file_analytics_analytics_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSalesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSalesSummary) ProtoMessage() {}

func (x *ProductSalesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSalesSummary.ProtoReflect.Descriptor instead.
func (*ProductSalesSummary) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{4}
}

func (x *ProductSalesSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductSalesSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ProductSalesSummary) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductSalesSummary) GetProductGroupId() int32 {
	if x != nil && x.ProductGroupId != nil {
		return *x.ProductGroupId
	}
	return 0
}

func (x *ProductSalesSummary) GetQuantitySold() int32 {
	if x != nil {
		return x.QuantitySold
	}
	return 0
}

func (x *ProductSalesSummary) GetGrossSales() string {
	if x != nil {
		return x.GrossSales
	}
	return ""
}

func (x *ProductSalesSummary) GetTotalDiscounts() string {
	if x != nil {
		return x.TotalDiscounts
	}
	return ""
}

func (x *ProductSalesSummary) GetNetSales() string {
	if x != nil {
		return x.NetSales
	}
	return ""
}

func (x *ProductSalesSummary) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

func (x *ProductSalesSummary) GetGrossProfit() string {
	if x != nil {
		return x.GrossProfit
	}
	return ""
}

func (x *ProductSalesSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductSalesSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EmployeePerformance struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date              string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	EmployeeId        int64                  `protobuf:"varint,3,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	TotalSales        string                 `protobuf:"bytes,4,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,5,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalItemsSold    int32                  `protobuf:"varint,6,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	CommissionEarned  string                 `protobuf:"bytes,7,opt,name=commission_earned,json=commissionEarned,proto3" json:"commission_earned,omitempty"`
	PerformanceScore  string                 `protobuf:"bytes,8,opt,name=performance_score,json=performanceScore,proto3" json:"performance_score,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmployeePerformance) Reset() {
	*x = EmployeePerformance{}
	mi := &file_analytics_analytics_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeePerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeePerformance) ProtoMessage() {}

func (x *EmployeePerformance) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeePerformance.ProtoReflect.Descriptor instead.
func (*EmployeePerformance) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{5}
}

func (x *EmployeePerformance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeePerformance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EmployeePerformance) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *EmployeePerformance) GetTotalSales() string {
	if x != nil {
		return x.TotalSales
	}
	return ""
}

func (x *EmployeePerformance) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *EmployeePerformance) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

func (x *EmployeePerformance) GetCommissionEarned() string {
	if x != nil {
		return x.CommissionEarned
	}
	return ""
}

func (x *EmployeePerformance) GetPerformanceScore() string {
	if x != nil {
		return x.PerformanceScore
	}
	return ""
}

func (x *EmployeePerformance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EmployeePerformance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CustomerAnalytics struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                    string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	ProductGroupId          *int32                 `protobuf:"varint,3,opt,name=product_group_id,json=productGroupId,proto3,oneof" json:"product_group_id,omitempty"`
	TotalTransactions       int32                  `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalRevenue            string                 `protobuf:"bytes,5,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AverageTransactionValue string                 `protobuf:"bytes,6,opt,name=average_transaction_value,json=averageTransactionValue,proto3" json:"average_transaction_value,omitempty"`
	PeakHour                *string                `protobuf:"bytes,7,opt,name=peak_hour,json=peakHour,proto3,oneof" json:"peak_hour,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CustomerAnalytics) Reset() {
	*x = CustomerAnalytics{}
	mi := &file_analytics_analytics_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerAnalytics) ProtoMessage() {}

func (x *CustomerAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerAnalytics.ProtoReflect.Descriptor instead.
func (*CustomerAnalytics) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{6}
}

func (x *CustomerAnalytics) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CustomerAnalytics) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CustomerAnalytics) GetProductGroupId() int32 {
	if x != nil && x.ProductGroupId != nil {
		return *x.ProductGroupId
	}
	return 0
}

func (x *CustomerAnalytics) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *CustomerAnalytics) GetTotalRevenue() string {
	if x != nil {
		return x.TotalRevenue
	}
	return ""
}

func (x *CustomerAnalytics) GetAverageTransactionValue() string {
	if x != nil {
		return x.AverageTransactionValue
	}
	return ""
}

func (x *CustomerAnalytics) GetPeakHour() string {
	if x != nil && x.PeakHour != nil {
		return *x.PeakHour
	}
	return ""
}

func (x *CustomerAnalytics) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CustomerAnalytics) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Aggregated reporting models
type SalesReport struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Period                  *DateRange             `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	TotalRevenue            string                 `protobuf:"bytes,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalCost               string                 `protobuf:"bytes,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	GrossProfit             string                 `protobuf:"bytes,4,opt,name=gross_profit,json=grossProfit,proto3" json:"gross_profit,omitempty"`
	ProfitMarginPercentage  string                 `protobuf:"bytes,5,opt,name=profit_margin_percentage,json=profitMarginPercentage,proto3" json:"profit_margin_percentage,omitempty"`
	TotalTransactions       int32                  `protobuf:"varint,6,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalItemsSold          int32                  `protobuf:"varint,7,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	AverageTransactionValue string                 `protobuf:"bytes,8,opt,name=average_transaction_value,json=averageTransactionValue,proto3" json:"average_transaction_value,omitempty"`
	DailyBreakdowns         []*SalesSummaryDaily   `protobuf:"bytes,9,rep,name=daily_breakdowns,json=dailyBreakdowns,proto3" json:"daily_breakdowns,omitempty"`
	TopProducts             []*ProductSalesSummary `protobuf:"bytes,10,rep,name=top_products,json=topProducts,proto3" json:"top_products,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SalesReport) Reset() {
	*x = SalesReport{}
	mi := &file_analytics_analytics_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesReport) ProtoMessage() {}

func (x *SalesReport) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesReport.ProtoReflect.Descriptor instead.
func (*SalesReport) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{7}
}

func (x *SalesReport) GetPeriod() *DateRange {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *SalesReport) GetTotalRevenue() string {
	if x != nil {
		return x.TotalRevenue
	}
	return ""
}

func (x *SalesReport) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

func (x *SalesReport) GetGrossProfit() string {
	if x != nil {
		return x.GrossProfit
	}
	return ""
}

func (x *SalesReport) GetProfitMarginPercentage() string {
	if x != nil {
		return x.ProfitMarginPercentage
	}
	return ""
}

func (x *SalesReport) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *SalesReport) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

func (x *SalesReport) GetAverageTransactionValue() string {
	if x != nil {
		return x.AverageTransactionValue
	}
	return ""
}

func (x *SalesReport) GetDailyBreakdowns() []*SalesSummaryDaily {
	if x != nil {
		return x.DailyBreakdowns
	}
	return nil
}

func (x *SalesReport) GetTopProducts() []*ProductSalesSummary {
	if x != nil {
		return x.TopProducts
	}
	return nil
}

type PerformanceReport struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Period                 *DateRange             `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	EmployeePerformances   []*EmployeePerformance `protobuf:"bytes,2,rep,name=employee_performances,json=employeePerformances,proto3" json:"employee_performances,omitempty"`
	TotalCommissions       string                 `protobuf:"bytes,3,opt,name=total_commissions,json=totalCommissions,proto3" json:"total_commissions,omitempty"`
	TopPerformerEmployeeId int64                  `protobuf:"varint,4,opt,name=top_performer_employee_id,json=topPerformerEmployeeId,proto3" json:"top_performer_employee_id,omitempty"`
	TopPerformerSales      string                 `protobuf:"bytes,5,opt,name=top_performer_sales,json=topPerformerSales,proto3" json:"top_performer_sales,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PerformanceReport) Reset() {
	*x = PerformanceReport{}
	mi := &file_analytics_analytics_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceReport) ProtoMessage() {}

func (x *PerformanceReport) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceReport.ProtoReflect.Descriptor instead.
func (*PerformanceReport) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{8}
}

func (x *PerformanceReport) GetPeriod() *DateRange {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *PerformanceReport) GetEmployeePerformances() []*EmployeePerformance {
	if x != nil {
		return x.EmployeePerformances
	}
	return nil
}

func (x *PerformanceReport) GetTotalCommissions() string {
	if x != nil {
		return x.TotalCommissions
	}
	return ""
}

func (x *PerformanceReport) GetTopPerformerEmployeeId() int64 {
	if x != nil {
		return x.TopPerformerEmployeeId
	}
	return 0
}

func (x *PerformanceReport) GetTopPerformerSales() string {
	if x != nil {
		return x.TopPerformerSales
	}
	return ""
}

// Sales Reporting
type GetSalesReportRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DateRange               *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	CashierId               *int64                 `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3,oneof" json:"cashier_id,omitempty"`
	ProductGroupId          *int32                 `protobuf:"varint,3,opt,name=product_group_id,json=productGroupId,proto3,oneof" json:"product_group_id,omitempty"`
	IncludeDailyBreakdown   *bool                  `protobuf:"varint,4,opt,name=include_daily_breakdown,json=includeDailyBreakdown,proto3,oneof" json:"include_daily_breakdown,omitempty"`
	IncludeProductBreakdown *bool                  `protobuf:"varint,5,opt,name=include_product_breakdown,json=includeProductBreakdown,proto3,oneof" json:"include_product_breakdown,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetSalesReportRequest) Reset() {
	*x = GetSalesReportRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesReportRequest) ProtoMessage() {}

func (x *GetSalesReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesReportRequest.ProtoReflect.Descriptor instead.
func (*GetSalesReportRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetSalesReportRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetSalesReportRequest) GetCashierId() int64 {
	if x != nil && x.CashierId != nil {
		return *x.CashierId
	}
	return 0
}

func (x *GetSalesReportRequest) GetProductGroupId() int32 {
	if x != nil && x.ProductGroupId != nil {
		return *x.ProductGroupId
	}
	return 0
}

func (x *GetSalesReportRequest) GetIncludeDailyBreakdown() bool {
	if x != nil && x.IncludeDailyBreakdown != nil {
		return *x.IncludeDailyBreakdown
	}
	return false
}

func (x *GetSalesReportRequest) GetIncludeProductBreakdown() bool {
	if x != nil && x.IncludeProductBreakdown != nil {
		return *x.IncludeProductBreakdown
	}
	return false
}

type GetSalesReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalesReport   *SalesReport           `protobuf:"bytes,1,opt,name=sales_report,json=salesReport,proto3" json:"sales_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesReportResponse) Reset() {
	*x = GetSalesReportResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesReportResponse) ProtoMessage() {}

func (x *GetSalesReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesReportResponse.ProtoReflect.Descriptor instead.
func (*GetSalesReportResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetSalesReportResponse) GetSalesReport() *SalesReport {
	if x != nil {
		return x.SalesReport
	}
	return nil
}

type GetDailySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CashierId     *int64                 `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3,oneof" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummaryRequest) Reset() {
	*x = GetDailySummaryRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryRequest) ProtoMessage() {}

func (x *GetDailySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDailySummaryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetDailySummaryRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDailySummaryRequest) GetCashierId() int64 {
	if x != nil && x.CashierId != nil {
		return *x.CashierId
	}
	return 0
}

type GetDailySummaryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DailySummaries []*SalesSummaryDaily   `protobuf:"bytes,1,rep,name=daily_summaries,json=dailySummaries,proto3" json:"daily_summaries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDailySummaryResponse) Reset() {
	*x = GetDailySummaryResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryResponse) ProtoMessage() {}

func (x *GetDailySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDailySummaryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetDailySummaryResponse) GetDailySummaries() []*SalesSummaryDaily {
	if x != nil {
		return x.DailySummaries
	}
	return nil
}

type GenerateDailySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CashierId     *int64                 `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3,oneof" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDailySummaryRequest) Reset() {
	*x = GenerateDailySummaryRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDailySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDailySummaryRequest) ProtoMessage() {}

func (x *GenerateDailySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDailySummaryRequest.ProtoReflect.Descriptor instead.
func (*GenerateDailySummaryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateDailySummaryRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GenerateDailySummaryRequest) GetCashierId() int64 {
	if x != nil && x.CashierId != nil {
		return *x.CashierId
	}
	return 0
}

type GenerateDailySummaryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GeneratedSummaries []*SalesSummaryDaily   `protobuf:"bytes,1,rep,name=generated_summaries,json=generatedSummaries,proto3" json:"generated_summaries,omitempty"`
	Success            bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message            *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateDailySummaryResponse) Reset() {
	*x = GenerateDailySummaryResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDailySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDailySummaryResponse) ProtoMessage() {}

func (x *GenerateDailySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDailySummaryResponse.ProtoReflect.Descriptor instead.
func (*GenerateDailySummaryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateDailySummaryResponse) GetGeneratedSummaries() []*SalesSummaryDaily {
	if x != nil {
		return x.GeneratedSummaries
	}
	return nil
}

func (x *GenerateDailySummaryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateDailySummaryResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Product Analytics
type GetProductSalesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DateRange      *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	ProductId      *int32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	ProductGroupId *int32                 `protobuf:"varint,3,opt,name=product_group_id,json=productGroupId,proto3,oneof" json:"product_group_id,omitempty"`
	Pagination     *PaginationRequest     `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProductSalesRequest) Reset() {
	*x = GetProductSalesRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSalesRequest) ProtoMessage() {}

func (x *GetProductSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSalesRequest.ProtoReflect.Descriptor instead.
func (*GetProductSalesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetProductSalesRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetProductSalesRequest) GetProductId() int32 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *GetProductSalesRequest) GetProductGroupId() int32 {
	if x != nil && x.ProductGroupId != nil {
		return *x.ProductGroupId
	}
	return 0
}

func (x *GetProductSalesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetProductSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductSales  []*ProductSalesSummary `protobuf:"bytes,1,rep,name=product_sales,json=productSales,proto3" json:"product_sales,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductSalesResponse) Reset() {
	*x = GetProductSalesResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSalesResponse) ProtoMessage() {}

func (x *GetProductSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSalesResponse.ProtoReflect.Descriptor instead.
func (*GetProductSalesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetProductSalesResponse) GetProductSales() []*ProductSalesSummary {
	if x != nil {
		return x.ProductSales
	}
	return nil
}

func (x *GetProductSalesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTopSellingProductsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DateRange      *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ProductGroupId *int32                 `protobuf:"varint,3,opt,name=product_group_id,json=productGroupId,proto3,oneof" json:"product_group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTopSellingProductsRequest) Reset() {
	*x = GetTopSellingProductsRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopSellingProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopSellingProductsRequest) ProtoMessage() {}

func (x *GetTopSellingProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopSellingProductsRequest.ProtoReflect.Descriptor instead.
func (*GetTopSellingProductsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetTopSellingProductsRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetTopSellingProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopSellingProductsRequest) GetProductGroupId() int32 {
	if x != nil && x.ProductGroupId != nil {
		return *x.ProductGroupId
	}
	return 0
}

type GetTopSellingProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopProducts   []*ProductSalesSummary `protobuf:"bytes,1,rep,name=top_products,json=topProducts,proto3" json:"top_products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopSellingProductsResponse) Reset() {
	*x = GetTopSellingProductsResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopSellingProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopSellingProductsResponse) ProtoMessage() {}

func (x *GetTopSellingProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopSellingProductsResponse.ProtoReflect.Descriptor instead.
func (*GetTopSellingProductsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetTopSellingProductsResponse) GetTopProducts() []*ProductSalesSummary {
	if x != nil {
		return x.TopProducts
	}
	return nil
}

// Employee Performance
type GetEmployeePerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateRange     *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	EmployeeId    *int64                 `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3,oneof" json:"employee_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeePerformanceRequest) Reset() {
	*x = GetEmployeePerformanceRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeePerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeePerformanceRequest) ProtoMessage() {}

func (x *GetEmployeePerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeePerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeePerformanceRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetEmployeePerformanceRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetEmployeePerformanceRequest) GetEmployeeId() int64 {
	if x != nil && x.EmployeeId != nil {
		return *x.EmployeeId
	}
	return 0
}

func (x *GetEmployeePerformanceRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetEmployeePerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Performances  []*EmployeePerformance `protobuf:"bytes,1,rep,name=performances,proto3" json:"performances,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeePerformanceResponse) Reset() {
	*x = GetEmployeePerformanceResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeePerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeePerformanceResponse) ProtoMessage() {}

func (x *GetEmployeePerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeePerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeePerformanceResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetEmployeePerformanceResponse) GetPerformances() []*EmployeePerformance {
	if x != nil {
		return x.Performances
	}
	return nil
}

func (x *GetEmployeePerformanceResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetPerformanceReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateRange     *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	EmployeeId    *int64                 `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3,oneof" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerformanceReportRequest) Reset() {
	*x = GetPerformanceReportRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceReportRequest) ProtoMessage() {}

func (x *GetPerformanceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceReportRequest.ProtoReflect.Descriptor instead.
func (*GetPerformanceReportRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetPerformanceReportRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetPerformanceReportRequest) GetEmployeeId() int64 {
	if x != nil && x.EmployeeId != nil {
		return *x.EmployeeId
	}
	return 0
}

type GetPerformanceReportResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PerformanceReport *PerformanceReport     `protobuf:"bytes,1,opt,name=performance_report,json=performanceReport,proto3" json:"performance_report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPerformanceReportResponse) Reset() {
	*x = GetPerformanceReportResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceReportResponse) ProtoMessage() {}

func (x *GetPerformanceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceReportResponse.ProtoReflect.Descriptor instead.
func (*GetPerformanceReportResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetPerformanceReportResponse) GetPerformanceReport() *PerformanceReport {
	if x != nil {
		return x.PerformanceReport
	}
	return nil
}

// Customer Analytics
type GetCustomerAnalyticsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DateRange      *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	ProductGroupId *int32                 `protobuf:"varint,2,opt,name=product_group_id,json=productGroupId,proto3,oneof" json:"product_group_id,omitempty"`
	Pagination     *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCustomerAnalyticsRequest) Reset() {
	*x = GetCustomerAnalyticsRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerAnalyticsRequest) ProtoMessage() {}

func (x *GetCustomerAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetCustomerAnalyticsRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetCustomerAnalyticsRequest) GetProductGroupId() int32 {
	if x != nil && x.ProductGroupId != nil {
		return *x.ProductGroupId
	}
	return 0
}

func (x *GetCustomerAnalyticsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetCustomerAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     []*CustomerAnalytics   `protobuf:"bytes,1,rep,name=analytics,proto3" json:"analytics,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerAnalyticsResponse) Reset() {
	*x = GetCustomerAnalyticsResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerAnalyticsResponse) ProtoMessage() {}

func (x *GetCustomerAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetCustomerAnalyticsResponse) GetAnalytics() []*CustomerAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

func (x *GetCustomerAnalyticsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetPeakHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateRange     *DateRange             `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeakHoursRequest) Reset() {
	*x = GetPeakHoursRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeakHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeakHoursRequest) ProtoMessage() {}

func (x *GetPeakHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeakHoursRequest.ProtoReflect.Descriptor instead.
func (*GetPeakHoursRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetPeakHoursRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

type GetPeakHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeakHours     []*PeakHourData        `protobuf:"bytes,1,rep,name=peak_hours,json=peakHours,proto3" json:"peak_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeakHoursResponse) Reset() {
	*x = GetPeakHoursResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeakHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeakHoursResponse) ProtoMessage() {}

func (x *GetPeakHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeakHoursResponse.ProtoReflect.Descriptor instead.
func (*GetPeakHoursResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetPeakHoursResponse) GetPeakHours() []*PeakHourData {
	if x != nil {
		return x.PeakHours
	}
	return nil
}

type PeakHourData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hour             string                 `protobuf:"bytes,1,opt,name=hour,proto3" json:"hour,omitempty"`
	TransactionCount int32                  `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	TotalRevenue     string                 `protobuf:"bytes,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeakHourData) Reset() {
	*x = PeakHourData{}
	mi := &file_analytics_analytics_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeakHourData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeakHourData) ProtoMessage() {}

func (x *PeakHourData) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeakHourData.ProtoReflect.Descriptor instead.
func (*PeakHourData) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{27}
}

func (x *PeakHourData) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *PeakHourData) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *PeakHourData) GetTotalRevenue() string {
	if x != nil {
		return x.TotalRevenue
	}
	return ""
}

type GetDashboardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardDataRequest) Reset() {
	*x = GetDashboardDataRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardDataRequest) ProtoMessage() {}

func (x *GetDashboardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardDataRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardDataRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{28}
}

func (x *GetDashboardDataRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetDashboardDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     *DashboardData         `protobuf:"bytes,1,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardDataResponse) Reset() {
	*x = GetDashboardDataResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardDataResponse) ProtoMessage() {}

func (x *GetDashboardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardDataResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardDataResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{29}
}

func (x *GetDashboardDataResponse) GetDashboard() *DashboardData {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

type DashboardData struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TodayRevenue                string                 `protobuf:"bytes,1,opt,name=today_revenue,json=todayRevenue,proto3" json:"today_revenue,omitempty"`
	TodayTransactions           int32                  `protobuf:"varint,2,opt,name=today_transactions,json=todayTransactions,proto3" json:"today_transactions,omitempty"`
	TodayItemsSold              int32                  `protobuf:"varint,3,opt,name=today_items_sold,json=todayItemsSold,proto3" json:"today_items_sold,omitempty"`
	TodayProfit                 string                 `protobuf:"bytes,4,opt,name=today_profit,json=todayProfit,proto3" json:"today_profit,omitempty"`
	RevenueChangePercentage     string                 `protobuf:"bytes,5,opt,name=revenue_change_percentage,json=revenueChangePercentage,proto3" json:"revenue_change_percentage,omitempty"`
	TransactionChangePercentage string                 `protobuf:"bytes,6,opt,name=transaction_change_percentage,json=transactionChangePercentage,proto3" json:"transaction_change_percentage,omitempty"`
	TopProductsToday            []*ProductSalesSummary `protobuf:"bytes,7,rep,name=top_products_today,json=topProductsToday,proto3" json:"top_products_today,omitempty"`
	TopPerformersToday          []*EmployeePerformance `protobuf:"bytes,8,rep,name=top_performers_today,json=topPerformersToday,proto3" json:"top_performers_today,omitempty"`
	LowStockAlerts              []string               `protobuf:"bytes,9,rep,name=low_stock_alerts,json=lowStockAlerts,proto3" json:"low_stock_alerts,omitempty"`
	PendingCommissionsCount     int32                  `protobuf:"varint,10,opt,name=pending_commissions_count,json=pendingCommissionsCount,proto3" json:"pending_commissions_count,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DashboardData) Reset() {
	*x = DashboardData{}
	mi := &file_analytics_analytics_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardData) ProtoMessage() {}

func (x *DashboardData) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardData.ProtoReflect.Descriptor instead.
func (*DashboardData) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{30}
}

func (x *DashboardData) GetTodayRevenue() string {
	if x != nil {
		return x.TodayRevenue
	}
	return ""
}

func (x *DashboardData) GetTodayTransactions() int32 {
	if x != nil {
		return x.TodayTransactions
	}
	return 0
}

func (x *DashboardData) GetTodayItemsSold() int32 {
	if x != nil {
		return x.TodayItemsSold
	}
	return 0
}

func (x *DashboardData) GetTodayProfit() string {
	if x != nil {
		return x.TodayProfit
	}
	return ""
}

func (x *DashboardData) GetRevenueChangePercentage() string {
	if x != nil {
		return x.RevenueChangePercentage
	}
	return ""
}

func (x *DashboardData) GetTransactionChangePercentage() string {
	if x != nil {
		return x.TransactionChangePercentage
	}
	return ""
}

func (x *DashboardData) GetTopProductsToday() []*ProductSalesSummary {
	if x != nil {
		return x.TopProductsToday
	}
	return nil
}

func (x *DashboardData) GetTopPerformersToday() []*EmployeePerformance {
	if x != nil {
		return x.TopPerformersToday
	}
	return nil
}

func (x *DashboardData) GetLowStockAlerts() []string {
	if x != nil {
		return x.LowStockAlerts
	}
	return nil
}

func (x *DashboardData) GetPendingCommissionsCount() int32 {
	if x != nil {
		return x.PendingCommissionsCount
	}
	return 0
}

type GetRealTimeMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealTimeMetricsRequest) Reset() {
	*x = GetRealTimeMetricsRequest{}
	mi := &file_analytics_analytics_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealTimeMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeMetricsRequest) ProtoMessage() {}

func (x *GetRealTimeMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetRealTimeMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{31}
}

type GetRealTimeMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *RealTimeMetrics       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealTimeMetricsResponse) Reset() {
	*x = GetRealTimeMetricsResponse{}
	mi := &file_analytics_analytics_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealTimeMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeMetricsResponse) ProtoMessage() {}

func (x *GetRealTimeMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetRealTimeMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{32}
}

func (x *GetRealTimeMetricsResponse) GetMetrics() *RealTimeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RealTimeMetrics struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	LastUpdated             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	ActiveTransactions      int32                  `protobuf:"varint,2,opt,name=active_transactions,json=activeTransactions,proto3" json:"active_transactions,omitempty"`
	HourlyRevenue           string                 `protobuf:"bytes,3,opt,name=hourly_revenue,json=hourlyRevenue,proto3" json:"hourly_revenue,omitempty"`
	HourlyTransactionCount  int32                  `protobuf:"varint,4,opt,name=hourly_transaction_count,json=hourlyTransactionCount,proto3" json:"hourly_transaction_count,omitempty"`
	AverageTransactionValue string                 `protobuf:"bytes,5,opt,name=average_transaction_value,json=averageTransactionValue,proto3" json:"average_transaction_value,omitempty"`
	RecentLargeTransactions []string               `protobuf:"bytes,6,rep,name=recent_large_transactions,json=recentLargeTransactions,proto3" json:"recent_large_transactions,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RealTimeMetrics) Reset() {
	*x = RealTimeMetrics{}
	mi := &file_analytics_analytics_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealTimeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealTimeMetrics) ProtoMessage() {}

func (x *RealTimeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealTimeMetrics.ProtoReflect.Descriptor instead.
func (*RealTimeMetrics) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_service_proto_rawDescGZIP(), []int{33}
}

func (x *RealTimeMetrics) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *RealTimeMetrics) GetActiveTransactions() int32 {
	if x != nil {
		return x.ActiveTransactions
	}
	return 0
}

func (x *RealTimeMetrics) GetHourlyRevenue() string {
	if x != nil {
		return x.HourlyRevenue
	}
	return ""
}

func (x *RealTimeMetrics) GetHourlyTransactionCount() int32 {
	if x != nil {
		return x.HourlyTransactionCount
	}
	return 0
}

func (x *RealTimeMetrics) GetAverageTransactionValue() string {
	if x != nil {
		return x.AverageTransactionValue
	}
	return ""
}

func (x *RealTimeMetrics) GetRecentLargeTransactions() []string {
	if x != nil {
		return x.RecentLargeTransactions
	}
	return nil
}

var File_analytics_analytics_service_proto protoreflect.FileDescriptor

const file_analytics_analytics_service_proto_rawDesc = "" +
	"\n" +
	"!analytics/analytics_service.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\x11PaginationRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"]\n" +
	"\x12PaginationResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"E\n" +
	"\tDateRange\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"\xeb\x03\n" +
	"\x11SalesSummaryDaily\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x03R\tcashierId\x12-\n" +
	"\x12total_transactions\x18\x04 \x01(\x05R\x11totalTransactions\x12(\n" +
	"\x10total_items_sold\x18\x05 \x01(\x05R\x0etotalItemsSold\x12\x1f\n" +
	"\vgross_sales\x18\x06 \x01(\tR\n" +
	"grossSales\x12'\n" +
	"\x0ftotal_discounts\x18\a \x01(\tR\x0etotalDiscounts\x12\x1b\n" +
	"\tnet_sales\x18\b \x01(\tR\bnetSales\x12\x1b\n" +
	"\ttotal_tax\x18\t \x01(\tR\btotalTax\x12\x1d\n" +
	"\n" +
	"total_cost\x18\n" +
	" \x01(\tR\ttotalCost\x12!\n" +
	"\fgross_profit\x18\v \x01(\tR\vgrossProfit\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x03\n" +
	"\x13ProductSalesSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12-\n" +
	"\x10product_group_id\x18\x04 \x01(\x05H\x00R\x0eproductGroupId\x88\x01\x01\x12#\n" +
	"\rquantity_sold\x18\x05 \x01(\x05R\fquantitySold\x12\x1f\n" +
	"\vgross_sales\x18\x06 \x01(\tR\n" +
	"grossSales\x12'\n" +
	"\x0ftotal_discounts\x18\a \x01(\tR\x0etotalDiscounts\x12\x1b\n" +
	"\tnet_sales\x18\b \x01(\tR\bnetSales\x12\x1d\n" +
	"\n" +
	"total_cost\x18\t \x01(\tR\ttotalCost\x12!\n" +
	"\fgross_profit\x18\n" +
	" \x01(\tR\vgrossProfit\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_product_group_id\"\xa4\x03\n" +
	"\x13EmployeePerformance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1f\n" +
	"\vemployee_id\x18\x03 \x01(\x03R\n" +
	"employeeId\x12\x1f\n" +
	"\vtotal_sales\x18\x04 \x01(\tR\n" +
	"totalSales\x12-\n" +
	"\x12total_transactions\x18\x05 \x01(\x05R\x11totalTransactions\x12(\n" +
	"\x10total_items_sold\x18\x06 \x01(\x05R\x0etotalItemsSold\x12+\n" +
	"\x11commission_earned\x18\a \x01(\tR\x10commissionEarned\x12+\n" +
	"\x11performance_score\x18\b \x01(\tR\x10performanceScore\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb1\x03\n" +
	"\x11CustomerAnalytics\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12-\n" +
	"\x10product_group_id\x18\x03 \x01(\x05H\x00R\x0eproductGroupId\x88\x01\x01\x12-\n" +
	"\x12total_transactions\x18\x04 \x01(\x05R\x11totalTransactions\x12#\n" +
	"\rtotal_revenue\x18\x05 \x01(\tR\ftotalRevenue\x12:\n" +
	"\x19average_transaction_value\x18\x06 \x01(\tR\x17averageTransactionValue\x12 \n" +
	"\tpeak_hour\x18\a \x01(\tH\x01R\bpeakHour\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_product_group_idB\f\n" +
	"\n" +
	"_peak_hour\"\xfd\x03\n" +
	"\vSalesReport\x12,\n" +
	"\x06period\x18\x01 \x01(\v2\x14.analytics.DateRangeR\x06period\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\tR\ftotalRevenue\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\tR\ttotalCost\x12!\n" +
	"\fgross_profit\x18\x04 \x01(\tR\vgrossProfit\x128\n" +
	"\x18profit_margin_percentage\x18\x05 \x01(\tR\x16profitMarginPercentage\x12-\n" +
	"\x12total_transactions\x18\x06 \x01(\x05R\x11totalTransactions\x12(\n" +
	"\x10total_items_sold\x18\a \x01(\x05R\x0etotalItemsSold\x12:\n" +
	"\x19average_transaction_value\x18\b \x01(\tR\x17averageTransactionValue\x12G\n" +
	"\x10daily_breakdowns\x18\t \x03(\v2\x1c.analytics.SalesSummaryDailyR\x0fdailyBreakdowns\x12A\n" +
	"\ftop_products\x18\n" +
	" \x03(\v2\x1e.analytics.ProductSalesSummaryR\vtopProducts\"\xae\x02\n" +
	"\x11PerformanceReport\x12,\n" +
	"\x06period\x18\x01 \x01(\v2\x14.analytics.DateRangeR\x06period\x12S\n" +
	"\x15employee_performances\x18\x02 \x03(\v2\x1e.analytics.EmployeePerformanceR\x14employeePerformances\x12+\n" +
	"\x11total_commissions\x18\x03 \x01(\tR\x10totalCommissions\x129\n" +
	"\x19top_performer_employee_id\x18\x04 \x01(\x03R\x16topPerformerEmployeeId\x12.\n" +
	"\x13top_performer_sales\x18\x05 \x01(\tR\x11topPerformerSales\"\xfb\x02\n" +
	"\x15GetSalesReportRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\x12\"\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x03H\x00R\tcashierId\x88\x01\x01\x12-\n" +
	"\x10product_group_id\x18\x03 \x01(\x05H\x01R\x0eproductGroupId\x88\x01\x01\x12;\n" +
	"\x17include_daily_breakdown\x18\x04 \x01(\bH\x02R\x15includeDailyBreakdown\x88\x01\x01\x12?\n" +
	"\x19include_product_breakdown\x18\x05 \x01(\bH\x03R\x17includeProductBreakdown\x88\x01\x01B\r\n" +
	"\v_cashier_idB\x13\n" +
	"\x11_product_group_idB\x1a\n" +
	"\x18_include_daily_breakdownB\x1c\n" +
	"\x1a_include_product_breakdown\"S\n" +
	"\x16GetSalesReportResponse\x129\n" +
	"\fsales_report\x18\x01 \x01(\v2\x16.analytics.SalesReportR\vsalesReport\"_\n" +
	"\x16GetDailySummaryRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\"\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x03H\x00R\tcashierId\x88\x01\x01B\r\n" +
	"\v_cashier_id\"`\n" +
	"\x17GetDailySummaryResponse\x12E\n" +
	"\x0fdaily_summaries\x18\x01 \x03(\v2\x1c.analytics.SalesSummaryDailyR\x0edailySummaries\"d\n" +
	"\x1bGenerateDailySummaryRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\"\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x03H\x00R\tcashierId\x88\x01\x01B\r\n" +
	"\v_cashier_id\"\xb2\x01\n" +
	"\x1cGenerateDailySummaryResponse\x12M\n" +
	"\x13generated_summaries\x18\x01 \x03(\v2\x1c.analytics.SalesSummaryDailyR\x12generatedSummaries\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\x82\x02\n" +
	"\x16GetProductSalesRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\x12\"\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05H\x00R\tproductId\x88\x01\x01\x12-\n" +
	"\x10product_group_id\x18\x03 \x01(\x05H\x01R\x0eproductGroupId\x88\x01\x01\x12<\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1c.analytics.PaginationRequestR\n" +
	"paginationB\r\n" +
	"\v_product_idB\x13\n" +
	"\x11_product_group_id\"\x9d\x01\n" +
	"\x17GetProductSalesResponse\x12C\n" +
	"\rproduct_sales\x18\x01 \x03(\v2\x1e.analytics.ProductSalesSummaryR\fproductSales\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.analytics.PaginationResponseR\n" +
	"pagination\"\xad\x01\n" +
	"\x1cGetTopSellingProductsRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12-\n" +
	"\x10product_group_id\x18\x03 \x01(\x05H\x00R\x0eproductGroupId\x88\x01\x01B\x13\n" +
	"\x11_product_group_id\"b\n" +
	"\x1dGetTopSellingProductsResponse\x12A\n" +
	"\ftop_products\x18\x01 \x03(\v2\x1e.analytics.ProductSalesSummaryR\vtopProducts\"\xc8\x01\n" +
	"\x1dGetEmployeePerformanceRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\x12$\n" +
	"\vemployee_id\x18\x02 \x01(\x03H\x00R\n" +
	"employeeId\x88\x01\x01\x12<\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1c.analytics.PaginationRequestR\n" +
	"paginationB\x0e\n" +
	"\f_employee_id\"\xa3\x01\n" +
	"\x1eGetEmployeePerformanceResponse\x12B\n" +
	"\fperformances\x18\x01 \x03(\v2\x1e.analytics.EmployeePerformanceR\fperformances\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.analytics.PaginationResponseR\n" +
	"pagination\"\x88\x01\n" +
	"\x1bGetPerformanceReportRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\x12$\n" +
	"\vemployee_id\x18\x02 \x01(\x03H\x00R\n" +
	"employeeId\x88\x01\x01B\x0e\n" +
	"\f_employee_id\"k\n" +
	"\x1cGetPerformanceReportResponse\x12K\n" +
	"\x12performance_report\x18\x01 \x01(\v2\x1c.analytics.PerformanceReportR\x11performanceReport\"\xd4\x01\n" +
	"\x1bGetCustomerAnalyticsRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\x12-\n" +
	"\x10product_group_id\x18\x02 \x01(\x05H\x00R\x0eproductGroupId\x88\x01\x01\x12<\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1c.analytics.PaginationRequestR\n" +
	"paginationB\x13\n" +
	"\x11_product_group_id\"\x99\x01\n" +
	"\x1cGetCustomerAnalyticsResponse\x12:\n" +
	"\tanalytics\x18\x01 \x03(\v2\x1c.analytics.CustomerAnalyticsR\tanalytics\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.analytics.PaginationResponseR\n" +
	"pagination\"J\n" +
	"\x13GetPeakHoursRequest\x123\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2\x14.analytics.DateRangeR\tdateRange\"N\n" +
	"\x14GetPeakHoursResponse\x126\n" +
	"\n" +
	"peak_hours\x18\x01 \x03(\v2\x17.analytics.PeakHourDataR\tpeakHours\"t\n" +
	"\fPeakHourData\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\tR\x04hour\x12+\n" +
	"\x11transaction_count\x18\x02 \x01(\x05R\x10transactionCount\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\tR\ftotalRevenue\"-\n" +
	"\x17GetDashboardDataRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"R\n" +
	"\x18GetDashboardDataResponse\x126\n" +
	"\tdashboard\x18\x01 \x01(\v2\x18.analytics.DashboardDataR\tdashboard\"\xb6\x04\n" +
	"\rDashboardData\x12#\n" +
	"\rtoday_revenue\x18\x01 \x01(\tR\ftodayRevenue\x12-\n" +
	"\x12today_transactions\x18\x02 \x01(\x05R\x11todayTransactions\x12(\n" +
	"\x10today_items_sold\x18\x03 \x01(\x05R\x0etodayItemsSold\x12!\n" +
	"\ftoday_profit\x18\x04 \x01(\tR\vtodayProfit\x12:\n" +
	"\x19revenue_change_percentage\x18\x05 \x01(\tR\x17revenueChangePercentage\x12B\n" +
	"\x1dtransaction_change_percentage\x18\x06 \x01(\tR\x1btransactionChangePercentage\x12L\n" +
	"\x12top_products_today\x18\a \x03(\v2\x1e.analytics.ProductSalesSummaryR\x10topProductsToday\x12P\n" +
	"\x14top_performers_today\x18\b \x03(\v2\x1e.analytics.EmployeePerformanceR\x12topPerformersToday\x12(\n" +
	"\x10low_stock_alerts\x18\t \x03(\tR\x0elowStockAlerts\x12:\n" +
	"\x19pending_commissions_count\x18\n" +
	" \x01(\x05R\x17pendingCommissionsCount\"\x1b\n" +
	"\x19GetRealTimeMetricsRequest\"R\n" +
	"\x1aGetRealTimeMetricsResponse\x124\n" +
	"\ametrics\x18\x01 \x01(\v2\x1a.analytics.RealTimeMetricsR\ametrics\"\xda\x02\n" +
	"\x0fRealTimeMetrics\x12=\n" +
	"\flast_updated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12/\n" +
	"\x13active_transactions\x18\x02 \x01(\x05R\x12activeTransactions\x12%\n" +
	"\x0ehourly_revenue\x18\x03 \x01(\tR\rhourlyRevenue\x128\n" +
	"\x18hourly_transaction_count\x18\x04 \x01(\x05R\x16hourlyTransactionCount\x12:\n" +
	"\x19average_transaction_value\x18\x05 \x01(\tR\x17averageTransactionValue\x12:\n" +
	"\x19recent_large_transactions\x18\x06 \x03(\tR\x17recentLargeTransactions2\xc4\b\n" +
	"\x10AnalyticsService\x12U\n" +
	"\x0eGetSalesReport\x12 .analytics.GetSalesReportRequest\x1a!.analytics.GetSalesReportResponse\x12X\n" +
	"\x0fGetDailySummary\x12!.analytics.GetDailySummaryRequest\x1a\".analytics.GetDailySummaryResponse\x12g\n" +
	"\x14GenerateDailySummary\x12&.analytics.GenerateDailySummaryRequest\x1a'.analytics.GenerateDailySummaryResponse\x12X\n" +
	"\x0fGetProductSales\x12!.analytics.GetProductSalesRequest\x1a\".analytics.GetProductSalesResponse\x12j\n" +
	"\x15GetTopSellingProducts\x12'.analytics.GetTopSellingProductsRequest\x1a(.analytics.GetTopSellingProductsResponse\x12m\n" +
	"\x16GetEmployeePerformance\x12(.analytics.GetEmployeePerformanceRequest\x1a).analytics.GetEmployeePerformanceResponse\x12g\n" +
	"\x14GetPerformanceReport\x12&.analytics.GetPerformanceReportRequest\x1a'.analytics.GetPerformanceReportResponse\x12g\n" +
	"\x14GetCustomerAnalytics\x12&.analytics.GetCustomerAnalyticsRequest\x1a'.analytics.GetCustomerAnalyticsResponse\x12O\n" +
	"\fGetPeakHours\x12\x1e.analytics.GetPeakHoursRequest\x1a\x1f.analytics.GetPeakHoursResponse\x12[\n" +
	"\x10GetDashboardData\x12\".analytics.GetDashboardDataRequest\x1a#.analytics.GetDashboardDataResponse\x12a\n" +
	"\x12GetRealTimeMetrics\x12$.analytics.GetRealTimeMetricsRequest\x1a%.analytics.GetRealTimeMetricsResponseB'Z%syntra-system/proto/protogen;protogenb\x06proto3"

var (
	file_analytics_analytics_service_proto_rawDescOnce sync.Once
	file_analytics_analytics_service_proto_rawDescData []byte
)

func file_analytics_analytics_service_proto_rawDescGZIP() []byte {
	file_analytics_analytics_service_proto_rawDescOnce.Do(func() {
		file_analytics_analytics_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_analytics_service_proto_rawDesc), len(file_analytics_analytics_service_proto_rawDesc)))
	})
	return file_analytics_analytics_service_proto_rawDescData
}

var file_analytics_analytics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_analytics_analytics_service_proto_goTypes = []any{
	(*PaginationRequest)(nil),              // 0: analytics.PaginationRequest
	(*PaginationResponse)(nil),             // 1: analytics.PaginationResponse
	(*DateRange)(nil),                      // 2: analytics.DateRange
	(*SalesSummaryDaily)(nil),              // 3: analytics.SalesSummaryDaily
	(*ProductSalesSummary)(nil),            // 4: analytics.ProductSalesSummary
	(*EmployeePerformance)(nil),            // 5: analytics.EmployeePerformance
	(*CustomerAnalytics)(nil),              // 6: analytics.CustomerAnalytics
	(*SalesReport)(nil),                    // 7: analytics.SalesReport
	(*PerformanceReport)(nil),              // 8: analytics.PerformanceReport
	(*GetSalesReportRequest)(nil),          // 9: analytics.GetSalesReportRequest
	(*GetSalesReportResponse)(nil),         // 10: analytics.GetSalesReportResponse
	(*GetDailySummaryRequest)(nil),         // 11: analytics.GetDailySummaryRequest
	(*GetDailySummaryResponse)(nil),        // 12: analytics.GetDailySummaryResponse
	(*GenerateDailySummaryRequest)(nil),    // 13: analytics.GenerateDailySummaryRequest
	(*GenerateDailySummaryResponse)(nil),   // 14: analytics.GenerateDailySummaryResponse
	(*GetProductSalesRequest)(nil),         // 15: analytics.GetProductSalesRequest
	(*GetProductSalesResponse)(nil),        // 16: analytics.GetProductSalesResponse
	(*GetTopSellingProductsRequest)(nil),   // 17: analytics.GetTopSellingProductsRequest
	(*GetTopSellingProductsResponse)(nil),  // 18: analytics.GetTopSellingProductsResponse
	(*GetEmployeePerformanceRequest)(nil),  // 19: analytics.GetEmployeePerformanceRequest
	(*GetEmployeePerformanceResponse)(nil), // 20: analytics.GetEmployeePerformanceResponse
	(*GetPerformanceReportRequest)(nil),    // 21: analytics.GetPerformanceReportRequest
	(*GetPerformanceReportResponse)(nil),   // 22: analytics.GetPerformanceReportResponse
	(*GetCustomerAnalyticsRequest)(nil),    // 23: analytics.GetCustomerAnalyticsRequest
	(*GetCustomerAnalyticsResponse)(nil),   // 24: analytics.GetCustomerAnalyticsResponse
	(*GetPeakHoursRequest)(nil),            // 25: analytics.GetPeakHoursRequest
	(*GetPeakHoursResponse)(nil),           // 26: analytics.GetPeakHoursResponse
	(*PeakHourData)(nil),                   // 27: analytics.PeakHourData
	(*GetDashboardDataRequest)(nil),        // 28: analytics.GetDashboardDataRequest
	(*GetDashboardDataResponse)(nil),       // 29: analytics.GetDashboardDataResponse
	(*DashboardData)(nil),                  // 30: analytics.DashboardData
	(*GetRealTimeMetricsRequest)(nil),      // 31: analytics.GetRealTimeMetricsRequest
	(*GetRealTimeMetricsResponse)(nil),     // 32: analytics.GetRealTimeMetricsResponse
	(*RealTimeMetrics)(nil),                // 33: analytics.RealTimeMetrics
	(*timestamppb.Timestamp)(nil),          // 34: google.protobuf.Timestamp
}
var file_analytics_analytics_service_proto_depIdxs = []int32{
	34, // 0: analytics.SalesSummaryDaily.created_at:type_name -> google.protobuf.Timestamp
	34, // 1: analytics.SalesSummaryDaily.updated_at:type_name -> google.protobuf.Timestamp
	34, // 2: analytics.ProductSalesSummary.created_at:type_name -> google.protobuf.Timestamp
	34, // 3: analytics.ProductSalesSummary.updated_at:type_name -> google.protobuf.Timestamp
	34, // 4: analytics.EmployeePerformance.created_at:type_name -> google.protobuf.Timestamp
	34, // 5: analytics.EmployeePerformance.updated_at:type_name -> google.protobuf.Timestamp
	34, // 6: analytics.CustomerAnalytics.created_at:type_name -> google.protobuf.Timestamp
	34, // 7: analytics.CustomerAnalytics.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: analytics.SalesReport.period:type_name -> analytics.DateRange
	3,  // 9: analytics.SalesReport.daily_breakdowns:type_name -> analytics.SalesSummaryDaily
	4,  // 10: analytics.SalesReport.top_products:type_name -> analytics.ProductSalesSummary
	2,  // 11: analytics.PerformanceReport.period:type_name -> analytics.DateRange
	5,  // 12: analytics.PerformanceReport.employee_performances:type_name -> analytics.EmployeePerformance
	2,  // 13: analytics.GetSalesReportRequest.date_range:type_name -> analytics.DateRange
	7,  // 14: analytics.GetSalesReportResponse.sales_report:type_name -> analytics.SalesReport
	3,  // 15: analytics.GetDailySummaryResponse.daily_summaries:type_name -> analytics.SalesSummaryDaily
	3,  // 16: analytics.GenerateDailySummaryResponse.generated_summaries:type_name -> analytics.SalesSummaryDaily
	2,  // 17: analytics.GetProductSalesRequest.date_range:type_name -> analytics.DateRange
	0,  // 18: analytics.GetProductSalesRequest.pagination:type_name -> analytics.PaginationRequest
	4,  // 19: analytics.GetProductSalesResponse.product_sales:type_name -> analytics.ProductSalesSummary
	1,  // 20: analytics.GetProductSalesResponse.pagination:type_name -> analytics.PaginationResponse
	2,  // 21: analytics.GetTopSellingProductsRequest.date_range:type_name -> analytics.DateRange
	4,  // 22: analytics.GetTopSellingProductsResponse.top_products:type_name -> analytics.ProductSalesSummary
	2,  // 23: analytics.GetEmployeePerformanceRequest.date_range:type_name -> analytics.DateRange
	0,  // 24: analytics.GetEmployeePerformanceRequest.pagination:type_name -> analytics.PaginationRequest
	5,  // 25: analytics.GetEmployeePerformanceResponse.performances:type_name -> analytics.EmployeePerformance
	1,  // 26: analytics.GetEmployeePerformanceResponse.pagination:type_name -> analytics.PaginationResponse
	2,  // 27: analytics.GetPerformanceReportRequest.date_range:type_name -> analytics.DateRange
	8,  // 28: analytics.GetPerformanceReportResponse.performance_report:type_name -> analytics.PerformanceReport
	2,  // 29: analytics.GetCustomerAnalyticsRequest.date_range:type_name -> analytics.DateRange
	0,  // 30: analytics.GetCustomerAnalyticsRequest.pagination:type_name -> analytics.PaginationRequest
	6,  // 31: analytics.GetCustomerAnalyticsResponse.analytics:type_name -> analytics.CustomerAnalytics
	1,  // 32: analytics.GetCustomerAnalyticsResponse.pagination:type_name -> analytics.PaginationResponse
	2,  // 33: analytics.GetPeakHoursRequest.date_range:type_name -> analytics.DateRange
	27, // 34: analytics.GetPeakHoursResponse.peak_hours:type_name -> analytics.PeakHourData
	30, // 35: analytics.GetDashboardDataResponse.dashboard:type_name -> analytics.DashboardData
	4,  // 36: analytics.DashboardData.top_products_today:type_name -> analytics.ProductSalesSummary
	5,  // 37: analytics.DashboardData.top_performers_today:type_name -> analytics.EmployeePerformance
	33, // 38: analytics.GetRealTimeMetricsResponse.metrics:type_name -> analytics.RealTimeMetrics
	34, // 39: analytics.RealTimeMetrics.last_updated:type_name -> google.protobuf.Timestamp
	9,  // 40: analytics.AnalyticsService.GetSalesReport:input_type -> analytics.GetSalesReportRequest
	11, // 41: analytics.AnalyticsService.GetDailySummary:input_type -> analytics.GetDailySummaryRequest
	13, // 42: analytics.AnalyticsService.GenerateDailySummary:input_type -> analytics.GenerateDailySummaryRequest
	15, // 43: analytics.AnalyticsService.GetProductSales:input_type -> analytics.GetProductSalesRequest
	17, // 44: analytics.AnalyticsService.GetTopSellingProducts:input_type -> analytics.GetTopSellingProductsRequest
	19, // 45: analytics.AnalyticsService.GetEmployeePerformance:input_type -> analytics.GetEmployeePerformanceRequest
	21, // 46: analytics.AnalyticsService.GetPerformanceReport:input_type -> analytics.GetPerformanceReportRequest
	23, // 47: analytics.AnalyticsService.GetCustomerAnalytics:input_type -> analytics.GetCustomerAnalyticsRequest
	25, // 48: analytics.AnalyticsService.GetPeakHours:input_type -> analytics.GetPeakHoursRequest
	28, // 49: analytics.AnalyticsService.GetDashboardData:input_type -> analytics.GetDashboardDataRequest
	31, // 50: analytics.AnalyticsService.GetRealTimeMetrics:input_type -> analytics.GetRealTimeMetricsRequest
	10, // 51: analytics.AnalyticsService.GetSalesReport:output_type -> analytics.GetSalesReportResponse
	12, // 52: analytics.AnalyticsService.GetDailySummary:output_type -> analytics.GetDailySummaryResponse
	14, // 53: analytics.AnalyticsService.GenerateDailySummary:output_type -> analytics.GenerateDailySummaryResponse
	16, // 54: analytics.AnalyticsService.GetProductSales:output_type -> analytics.GetProductSalesResponse
	18, // 55: analytics.AnalyticsService.GetTopSellingProducts:output_type -> analytics.GetTopSellingProductsResponse
	20, // 56: analytics.AnalyticsService.GetEmployeePerformance:output_type -> analytics.GetEmployeePerformanceResponse
	22, // 57: analytics.AnalyticsService.GetPerformanceReport:output_type -> analytics.GetPerformanceReportResponse
	24, // 58: analytics.AnalyticsService.GetCustomerAnalytics:output_type -> analytics.GetCustomerAnalyticsResponse
	26, // 59: analytics.AnalyticsService.GetPeakHours:output_type -> analytics.GetPeakHoursResponse
	29, // 60: analytics.AnalyticsService.GetDashboardData:output_type -> analytics.GetDashboardDataResponse
	32, // 61: analytics.AnalyticsService.GetRealTimeMetrics:output_type -> analytics.GetRealTimeMetricsResponse
	51, // [51:62] is the sub-list for method output_type
	40, // [40:51] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_analytics_analytics_service_proto_init() }
func file_analytics_analytics_service_proto_init() {
	if File_analytics_analytics_service_proto != nil {
		return
	}
	file_analytics_analytics_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[14].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[19].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[21].OneofWrappers = []any{}
	file_analytics_analytics_service_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_analytics_service_proto_rawDesc), len(file_analytics_analytics_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_analytics_service_proto_goTypes,
		DependencyIndexes: file_analytics_analytics_service_proto_depIdxs,
		MessageInfos:      file_analytics_analytics_service_proto_msgTypes,
	}.Build()
	File_analytics_analytics_service_proto = out.File
	file_analytics_analytics_service_proto_goTypes = nil
	file_analytics_analytics_service_proto_depIdxs = nil
}
