# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from analytics import analytics_service_pb2 as analytics_dot_analytics__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analytics/analytics_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSalesReport = channel.unary_unary(
                '/analytics.AnalyticsService/GetSalesReport',
                request_serializer=analytics_dot_analytics__service__pb2.GetSalesReportRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetSalesReportResponse.FromString,
                _registered_method=True)
        self.GetDailySummary = channel.unary_unary(
                '/analytics.AnalyticsService/GetDailySummary',
                request_serializer=analytics_dot_analytics__service__pb2.GetDailySummaryRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetDailySummaryResponse.FromString,
                _registered_method=True)
        self.GenerateDailySummary = channel.unary_unary(
                '/analytics.AnalyticsService/GenerateDailySummary',
                request_serializer=analytics_dot_analytics__service__pb2.GenerateDailySummaryRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GenerateDailySummaryResponse.FromString,
                _registered_method=True)
        self.GetProductSales = channel.unary_unary(
                '/analytics.AnalyticsService/GetProductSales',
                request_serializer=analytics_dot_analytics__service__pb2.GetProductSalesRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetProductSalesResponse.FromString,
                _registered_method=True)
        self.GetTopSellingProducts = channel.unary_unary(
                '/analytics.AnalyticsService/GetTopSellingProducts',
                request_serializer=analytics_dot_analytics__service__pb2.GetTopSellingProductsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetTopSellingProductsResponse.FromString,
                _registered_method=True)
        self.GetEmployeePerformance = channel.unary_unary(
                '/analytics.AnalyticsService/GetEmployeePerformance',
                request_serializer=analytics_dot_analytics__service__pb2.GetEmployeePerformanceRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetEmployeePerformanceResponse.FromString,
                _registered_method=True)
        self.GetPerformanceReport = channel.unary_unary(
                '/analytics.AnalyticsService/GetPerformanceReport',
                request_serializer=analytics_dot_analytics__service__pb2.GetPerformanceReportRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetPerformanceReportResponse.FromString,
                _registered_method=True)
        self.GetCustomerAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetCustomerAnalytics',
                request_serializer=analytics_dot_analytics__service__pb2.GetCustomerAnalyticsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetCustomerAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetPeakHours = channel.unary_unary(
                '/analytics.AnalyticsService/GetPeakHours',
                request_serializer=analytics_dot_analytics__service__pb2.GetPeakHoursRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetPeakHoursResponse.FromString,
                _registered_method=True)
        self.GetDashboardData = channel.unary_unary(
                '/analytics.AnalyticsService/GetDashboardData',
                request_serializer=analytics_dot_analytics__service__pb2.GetDashboardDataRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetDashboardDataResponse.FromString,
                _registered_method=True)
        self.GetRealTimeMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetRealTimeMetrics',
                request_serializer=analytics_dot_analytics__service__pb2.GetRealTimeMetricsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetRealTimeMetricsResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSalesReport(self, request, context):
        """Sales Analytics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDailySummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDailySummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductSales(self, request, context):
        """Product Analytics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopSellingProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeePerformance(self, request, context):
        """Employee Performance Analytics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerformanceReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomerAnalytics(self, request, context):
        """Customer Analytics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeakHours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboardData(self, request, context):
        """Dashboard and Real-time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealTimeMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSalesReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesReport,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetSalesReportRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetSalesReportResponse.SerializeToString,
            ),
            'GetDailySummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailySummary,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetDailySummaryRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetDailySummaryResponse.SerializeToString,
            ),
            'GenerateDailySummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDailySummary,
                    request_deserializer=analytics_dot_analytics__service__pb2.GenerateDailySummaryRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GenerateDailySummaryResponse.SerializeToString,
            ),
            'GetProductSales': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductSales,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetProductSalesRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetProductSalesResponse.SerializeToString,
            ),
            'GetTopSellingProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopSellingProducts,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetTopSellingProductsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetTopSellingProductsResponse.SerializeToString,
            ),
            'GetEmployeePerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeePerformance,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetEmployeePerformanceRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetEmployeePerformanceResponse.SerializeToString,
            ),
            'GetPerformanceReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerformanceReport,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetPerformanceReportRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetPerformanceReportResponse.SerializeToString,
            ),
            'GetCustomerAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerAnalytics,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetCustomerAnalyticsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetCustomerAnalyticsResponse.SerializeToString,
            ),
            'GetPeakHours': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeakHours,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetPeakHoursRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetPeakHoursResponse.SerializeToString,
            ),
            'GetDashboardData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardData,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetDashboardDataRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetDashboardDataResponse.SerializeToString,
            ),
            'GetRealTimeMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeMetrics,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetRealTimeMetricsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetRealTimeMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSalesReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetSalesReport',
            analytics_dot_analytics__service__pb2.GetSalesReportRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetSalesReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDailySummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetDailySummary',
            analytics_dot_analytics__service__pb2.GetDailySummaryRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetDailySummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDailySummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GenerateDailySummary',
            analytics_dot_analytics__service__pb2.GenerateDailySummaryRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GenerateDailySummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductSales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetProductSales',
            analytics_dot_analytics__service__pb2.GetProductSalesRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetProductSalesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopSellingProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTopSellingProducts',
            analytics_dot_analytics__service__pb2.GetTopSellingProductsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetTopSellingProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeePerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetEmployeePerformance',
            analytics_dot_analytics__service__pb2.GetEmployeePerformanceRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetEmployeePerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPerformanceReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetPerformanceReport',
            analytics_dot_analytics__service__pb2.GetPerformanceReportRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetPerformanceReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomerAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCustomerAnalytics',
            analytics_dot_analytics__service__pb2.GetCustomerAnalyticsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetCustomerAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeakHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetPeakHours',
            analytics_dot_analytics__service__pb2.GetPeakHoursRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetPeakHoursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboardData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetDashboardData',
            analytics_dot_analytics__service__pb2.GetDashboardDataRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetDashboardDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRealTimeMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetRealTimeMetrics',
            analytics_dot_analytics__service__pb2.GetRealTimeMetricsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetRealTimeMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
