"""Add raw_sales_events table

Revision ID: 71f58c76dee5
Revises: e555a22f56b8
Create Date: 2025-11-09 18:36:56.798513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f58c76dee5'
down_revision: Union[str, Sequence[str], None] = 'e555a22f56b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_sales_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_document_number', sa.String(length=255), nullable=False),
    sa.Column('order_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cashier_id', sa.BigInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_document_number')
    )
    op.create_index('idx_raw_sales_events_order_timestamp', 'raw_sales_events', ['order_timestamp'], unique=False)
    op.create_index(op.f('ix_raw_sales_events_order_timestamp'), 'raw_sales_events', ['order_timestamp'], unique=False)
    # op.alter_column('sales_summary_daily', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_summary_daily', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_raw_sales_events_order_timestamp'), table_name='raw_sales_events')
    op.drop_index('idx_raw_sales_events_order_timestamp', table_name='raw_sales_events')
    op.drop_table('raw_sales_events')
    # ### end Alembic commands ###
